name = "No Framework"
description = "When you use No Framework but you still like conventions"
license = "MIT"
homepage = "http://no-framework.com/"
min_version = "0.0.1"
demo = "http://no-framework.com/"

[author]
name = "Brian Graham"
homepage = "https://github.com/Incognito"
